//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comercio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comercio()
        {
            this.empleado = new HashSet<empleado>();
        }
    
        public int id_comercio { get; set; }
        public string razon_social { get; set; }
        public string ingresos_brutos { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public string CUIT { get; set; }
        public string estado { get; set; }
        public Nullable<int> IVA { get; set; }
    
        public virtual situacion_iva situacion_iva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleado { get; set; }
    }
}
