//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas
    {
        public int id_venta { get; set; }
        public int id_comercio { get; set; }
        public int id_empleado { get; set; }
        public int id_factura { get; set; }
    
        public virtual facturas facturas { get; set; }
    }
}
